### ISSUE TITLE
`@functools.total_ordering`

### ISSUE THREAD

**Issue by mentalisttraceur** [mentalisttraceur/python-macaddress#11]
If someone came to me in code review at a job with all four of `__lt__`, `__le__`, `__gt__`, and `__ge__` implemented, I'd immediately say "delete three of them and just use `@functools.total_ordering`: less potential for error, better signal-to-noise when reading code, [...]".

So is there a good enough reason for me to keep not applying my own advice to library code like this?

**Comment by mentalisttraceur** [comment]
So the "standard" (mentioned by the Python documentation itself) reasons against using `@functools.total_ordering` are:

1. Miniscule performance overhead.
2. Slightly more complicated stack traces.

**Comment by mentalisttraceur** [comment]
Other reasons against using `@functools.total_ordering` are:

3. Portability minimalism/conservatism - "what if someone wants to use this on a Python implementation where `functools.total_ordering` is not available and isn't easy to polyfill?

**Comment by mentalisttraceur** [comment]
Counters to the above reasons:

1. Use PyPy. Use an optimizing "compiler" that compiles Python source with the total ordering decorator into Python source with each method. Convert the logic in your hot loops to another language with state-of-the-art optimizing compilers or JIT compiling VMs. If performance matters _that much_, human effort is better spent on automated tooling to apply optimizations more generally and more automatically, than on the repetition of those optimizations in countless instantiations across the world's source code.
2. This too could actually be "optimized" out, in principle, if there was a good reason for it.
3. Once again, this kind of stuff is best fixed at other layers, in more general and automated ways.

Notably, a tool that can change the source code from the total ordering decorator and one of the ordering methods into all four ordering methods solves all three of the above issues, and the simpler and clearer the one method is, the easier it is to generate optimal versions of the other three.

**Comment by mentalisttraceur** [comment]
Fixed/implemented in f1d16b3983c851abbbc46e55239de8d3a709c2a5.

**Comment by gytqby** [comment]
> If it's not worth it to take the time to write such a tool, why is it worth it to make the source code worse for reading, maintenance, and verification?

I just want to say that I wholeheartedly agree.

**Comment by mentalisttraceur** [comment]
I just realized a super annoying thing: in comment reactions, GitHub calls the 😄 emoji "laugh" instead of something like "smile"/"joy":
![2022-05-10 15_26_58-`@functools total_ordering` · Issue #11 · mentalisttraceur_python-macaddress - q](https://user-images.githubusercontent.com/6531708/167706860-34037b0f-a2f5-48ba-99f8-5995fee2a22b.png)
